app/src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
	/**
	 * @ORM\Id
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private int $id;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private string $name;

	/**
	 * @ORM\OneToMany(targetEntity=Product::class, mappedBy="category")
	 */
	private Collection $products;

	public function getId(): int
	{
		return $this->id;
	}

	public function getName(): string
	{
		return $this->name;
	}

	public function setName(string $name): self
	{
		$this->name = $name;

		return $this;
	}

	/**
	 * @return Collection|Product[]
	 */
	public function getProducts(): Collection
	{
		return $this->products;
	}
}

app/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
	/**
	 * @ORM\Id
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private int $id;

	/**
	 * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
	 * @ORM\JoinColumn(nullable=false)
	 */
	private Category $category;

	/**
	 * @ORM\Column(type="integer")
	 */
	private int $price;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private string $name;

	/**
	 * @ORM\Column(type="date")
	 */
	private DateTime $createdAt;

	public function getId(): int
	{
		return $this->id;
	}

	public function getCategory(): Category
	{
		return $this->category;
	}

	public function setCategory(Category $category): self
	{
		$this->category = $category;

		return $this;
	}

	public function getPrice(): int
	{
		return $this->price;
	}

	public function setPrice(int $price): self
	{
		$this->price = $price;

		return $this;
	}

	public function getName(): string
	{
		return $this->name;
	}

	public function setName(string $name): self
	{
		$this->name = $name;

		return $this;
	}

	public function getCreatedAt(): DateTime
	{
		return $this->createdAt;
	}

	public function setCreatedAt(DateTime $createdAt): self
	{
		$this->createdAt = $createdAt;

		return $this;
	}

	public function getPriceFormatted(): string
	{
		return number_format($this->price / 100, 2, '.', ' ');
	}
}

app/src/Controller/CategoriesArrayController.php
<?php

namespace App\Controller;

use App\Handlers\BuildCategoriesArrayHandler;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class CategoriesArrayController extends AbstractController
{
	/**
	 * @Route("/categories/array", name="app_categories_array")
	 * @throws \Doctrine\DBAL\Exception
	 */
    public function buildCategoriesArray(BuildCategoriesArrayHandler $handler)
    {
		$timeStart = microtime(true);
		$categories = $handler->run();

		dump($categories);
		dd(microtime(true) - $timeStart);
    }
}

app/src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Handlers\GetCurrentCategoryAndProductsHandler;
use App\Handlers\GetProductByIdHandler;
use App\Handlers\GetCategoriesAndProductsHandler;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
	/**
     * @Route("", name="app-main")
     */
    public function index(Request $request, GetCategoriesAndProductsHandler $handler): Response
	{
		$categoryId = $request->query->get('c') ?: 0;
		$sort = $request->query->get('sort') ?? '';

		$response = $handler->run($categoryId, $sort);

		return $this->render('base.html.twig', array_merge(
			[
				'currentCategoryId' => $categoryId,
				'currentSort' => $sort,
			],
			$response
		));
    }

	/**
	 * @Route("/category/{id}/{sort}", name="category-by-id", methods={"GET"})
	 */
	public function showCategory(int $id, GetCurrentCategoryAndProductsHandler $handler, string $sort = ''): JsonResponse
	{
		return $this->json($handler->run($id, $sort));
	}

	/**
	 * @Route("/product/{id}", name="product-details", requirements={"id"="\d+"}, methods={"GET"})
	 */
	public function showOneProduct(int $id, GetProductByIdHandler $handler): JsonResponse
	{
		return $this->json($handler->run($id));
	}
}

app/templates/base.html.twig
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script>
        let currentCategoryId = {{ currentCategoryId }};
        let currentSort = '{{ currentSort }}';
    </script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">
            <ul>
                {% for category in categories %}
                    <li onclick="changeCategory({{ category.id }})" style="cursor: pointer">
                        {{ category.name }} ({{ category.products.count }})
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-9">
            <h3 id="productsListCaption">{{ currentCategory.name|default('Всі продукти') }}</h3>
            <label for="sort">Сортування:</label>
            <select id="sort" name="sort" onchange="changeSort(this)" class="form-select form-select-sm"
                    style="display: inline-block; width: auto">
                <option value="price"{% if currentSort == 'price' %} selected{% endif %}>спочатку дешевші</option>
                <option value="name"{% if currentSort == 'name' %} selected{% endif %}>за алфавітом</option>
                <option value="date"{% if currentSort == 'date' %} selected{% endif %}>спочатку нові</option>
            </select>
            <div id="productsWrapper">
                {% for product in products %}
                    <div class="p-2">
                        <p class="lead">{{ product.name }}</p>
                        {{ product.priceFormatted }} грн.<br>
                        {{ product.createdAt|date('d.m.Y') }}<br>
                        <button class="btn btn-primary btn-sm" onclick="showProductDetails({{ product.id }})">Купити</button>
                    </div>
                {% else %}
                    <div>Жодного продукту не знайдено в категорії</div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="productModal" tabindex="-1" aria-labelledby="productModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="productModalLabel">Інформація про товар</h5>
            </div>
            <div class="modal-body">
                <p>Ціна: <span id="productModalPrice"></span> грн.</p>
                <p>Дата додавання у каталог: <span id="productModalCreatedDate"></span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрити</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
        integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
<script src="/js/catalog.js"></script>
</body>
</html>